# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build-landing:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.16

    working_directory: ~/repo/landing

    steps:
      - checkout:
          path: ~/repo

      # Download and cache dependencies
      # - restore_cache:
      #     keys:
      #       - v1-dependencies-{{ checksum "package.json" }}
      # fallback to using the latest cache if no exact match is found
      # - v1-dependencies-

      - run:
          name: Install create-elm-app
          # Set unsafe-perm to true to suppress the UID/GID switching when running package scripts. If set explicitly to false, then installing as a non-root user will fail.
          command: sudo npm install -g create-elm-app@4.0.0 --unsafe-perm=true

      - run: elm-app build

workflows:
  version: 2
  build:
    jobs:
      - build-landing
