# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1

# Reuse this executor (docker image) between jobs
# https://circleci.com/docs/2.0/reusing-config/#authoring-reusable-executors
executors:
  landing-page-executor:
    docker:
      - image: circleci/node:10.16
    working_directory: ~/repo/landing

jobs:
  build-landing:
    executor: landing-page-executor
    steps:
      - checkout:
          path: ~/repo

      - run:
          name: Install create-elm-app
          # Set unsafe-perm to true to suppress the UID/GID switching when running package scripts. If set explicitly to false, then installing as a non-root user will fail.
          command: sudo npm install -g create-elm-app@4.0.0 --unsafe-perm=true

      - run: elm-app build

      # Persist build folder to the worksapce for deploy job
      - persist_to_workspace:
          root: ./
          paths:
            - build

  deploy-landing:
    executor: landing-page-executor
    steps:
      - attach_workspace:
          at: ~/repo/landing

      - run: ls

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-landing
      - deploy-landing:
          type: approval
          requires:
            - build-landing
          filters:
            branches:
              only: master
