# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1

# Reuse this executor (docker image) between jobs
# https://circleci.com/docs/2.0/reusing-config/#authoring-reusable-executors
executors:
  landing-page-executor:
    docker:
      - image: circleci/node:10.16
    working_directory: ~/repo/landing

  frontend-executor:
    docker:
      - image: circleci/node:10.16
    working_directory: ~/repo/frontend

jobs:
  build-landing:
    executor: landing-page-executor
    steps:
      - checkout:
          path: ~/repo

      - run:
          name: Install dependencies
          # Set unsafe-perm to true to suppress the UID/GID switching when running package scripts. If set explicitly to false, then installing as a non-root user will fail.
          command: sudo yarn install

      - run: 
          name: Build production application
          command: sudo yarn build:prod

  deploy-landing:
    executor: landing-page-executor
    steps:

      - add_ssh_keys:
          fingerprints:
            - 'a5:7a:8f:d8:2e:2f:09:40:89:b8:89:ce:58:f4:98:f7'

      - run:
          name: Pull latest code and restart landing
          command: ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ubuntu@52.198.50.117 "cd /home/node/app && git fetch origin && git reset --hard origin/master && docker-compose restart landing"

  build-frontend:
    executor: frontend-executor
    steps:
      - checkout:
          path: ~/repo

      - run:
          name: Install dependencies
          command: sudo yarn install

      - run:
          name: Build application
          command: sudo WORDPRESS_URL=https://dummy-wordpress.com yarn build

  deploy-frontend:
    executor: frontend-executor
    steps:
      - add_ssh_keys:
          fingerprints:
            - 'a5:7a:8f:d8:2e:2f:09:40:89:b8:89:ce:58:f4:98:f7'

      - run:
          name: Pull latest code and restart frontend
          command: ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ubuntu@52.198.50.117 "cd /home/ubuntu/app && git fetch origin && git reset --hard origin/master && docker-compose restart frontend"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-landing
      - build-frontend
      - deploy-landing:
          requires:
            - build-landing
          filters:
            branches:
              only: master
      - deploy-frontend:
          requires:
            - build-frontend
          filters:
            branches:
              only: master
